/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calliope_AeseSpeller */

#ifndef _Included_calliope_AeseSpeller
#define _Included_calliope_AeseSpeller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calliope_AeseSpeller
 * Method:    initialise
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_calliope_AeseSpeller_initialise
  (JNIEnv *, jobject, jstring);

/*
 * Class:     calliope_AeseSpeller
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_calliope_AeseSpeller_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     calliope_AeseSpeller
 * Method:    hasWord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_calliope_AeseSpeller_hasWord
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     calliope_AeseSpeller
 * Method:    listDicts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_calliope_AeseSpeller_listDicts
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
