/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calliope_AeseStripper */

#ifndef _Included_calliope_AeseStripper
#define _Included_calliope_AeseStripper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calliope_AeseStripper
 * Method:    strip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcalliope/json/JSONResponse;Lcalliope/json/JSONResponse;)I
 */
JNIEXPORT jint JNICALL Java_calliope_AeseStripper_strip
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     calliope_AeseStripper
 * Method:    formats
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_calliope_AeseStripper_formats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif