/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hritserver_HritStripper */

#ifndef _Included_hritserver_HritStripper
#define _Included_hritserver_HritStripper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hritserver_HritStripper
 * Method:    strip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lhritserver/JSONResponse;Lhritserver/JSONResponse;)I
 */
JNIEXPORT jint JNICALL Java_hritserver_HritStripper_strip
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     hritserver_HritStripper
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hritserver_HritStripper_version
  (JNIEnv *, jobject);

/*
 * Class:     hritserver_HritStripper
 * Method:    formats
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_hritserver_HritStripper_formats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
